### ISSUE TITLE
Compatibility with azure functions cli

### ISSUE THREAD

**Issue by davidtme** [tamizhvendan/Suave.Azure.Functions#3]
### Description

I have a very small run script bit it doesn’t seem to work with [azure functions cli]( https://github.com/Azure/azure-functions-cli) throwing the following error when I send a `GET` request:

```
Job host started
Http Function HelloSuaveAzureFun: http://localhost:7071/api/HelloSuaveAzureFun
Executing 'Functions.HelloSuaveAzureFun' (Reason='This function was programmatic
ally called via the host APIs.', Id=adf78fb8-c04c-4c62-af69-918a24bb041a)
Function started (Id=adf78fb8-c04c-4c62-af69-918a24bb041a)
Function completed (Failure, Id=adf78fb8-c04c-4c62-af69-918a24bb041a)

A ScriptHost error has occurred
Exception while executing function: Functions.HelloSuaveAzureFun. mscorlib: Exce
ption has been thrown by the target of an invocation. Suave.Azure.Functions: Met
hod not found: 'Microsoft.FSharp.Collections.FSharpList`1<HttpUpload> HttpReques
t.get_files()'.
```

### Repro steps

__run.fsx__
```F#
open System.Net.Http
open Suave.Azure.Functions.Context

open Suave
open Suave.Successful
open Suave.Operators
open Suave.Filters

let app = choose [ GET >=> OK "GET test" ]

let Run (req : HttpRequestMessage, log : TraceWriter) =
    let res = runWebPart app req |> Async.RunSynchronously
    res
```
__project.json__
```JSON
{
  "frameworks": {
    "net46": {
      "dependencies": {
        "Suave": "1.1.3",
        "Suave.Azure.Functions": "0.0.9"
      }
    }
  }
}
```

__function.json__
```JSON
{
  "disabled": false,
  "bindings": [
    {
      "type": "httpTrigger",
      "name": "req",
      "methods": [
        "get"
      ],
      "authLevel": "anonymous",
      "direction": "in"
    },
    {
      "type": "http",
      "name": "res",
      "direction": "out"
    }
  ]
}
```

* Windows
* azure-functions-cli v1.0.0-beta.92

**Comment by tamizhvendan** [comment]
@davidtme It seems like an issue with `azure functions cli`. Have you tried the same code in Azure Functions Portal?

**Comment by davidtme** [comment]
Thanks @tamizhvendan for the really fast response :)

I get a different error on Azure Functions Portal but it doesn't look very helpful or I have just set it up wrong:

```
...nd of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by tamizhvendan** [comment]
It's working in Azure Functions Portal. Can you try this simple one? https://gist.github.com/tamizhvendan/07fc54c3750d154a84ba7d6ccdb94eb6

**Comment by tamizhvendan** [comment]
@davidtme Can I close this issue?

**Comment by davidtme** [comment]
@tamizhvendan sure, this is a problem with the cli
